### ISSUE TITLE
phash.hash[-1] = False,  lost a line of feature?

### ISSUE THREAD

**Issue by chushuai** [meedan/alegre#30]
https://github.com/meedan/alegre/blob/093485b4ac730626151494524653061298f1f685/app/main/lib/image_hash.py#L36

the int65 range
9223372036854775807 ~  -9223372036854775808

**Comment by abraham-john-paul** [comment]
Hi could you please explain this issue?

**Comment by abraham-john-paul** [comment]
Does this count in Hcktoberfest?

**Comment by infojunkie** [comment]
We've inherited that code from a third-party source, so I'm not sure if resetting the last bit is intentional. If you think this is a bug, please submit a unit test that proves it - and yes in this case it will count for Hacktober Fest. Thanks!

**Comment by infojunkie** [comment]
@adamhrv could you advise here please?

**Comment by abraham-john-paul** [comment]
i'll try to write a unit test for this function
i'm new to unittest in python
Can i proceed with this?

**Comment by julescarbon** [comment]
Hey there!  I believe I added this line when we first started using the Imagehash library in 2018. I was trying to store the `phash.hash` in a MySQL table, so I had to convert the bool array into a BigInt.  I recall having problems inserting the Bigints, but setting this bit to false seemed to fix it.  Probably if I had specified an unsigned Bigint in the MySQL schema, it would have solve my problem without resorting to this mysterious hack.

Listen, folks, you gotta excuse me, I'm a UI developer mainly - I guess I bit off more than I could chew with this one!  I'm such a UI developer, I thought hamming distance was how far you had to walk from the supermarket entrance to the meat section.  Just kidding, I'm vegetarian!  I guess you could call it a tempeh-rary solution!  But seriously, folks, in practice, masking this bit only made a little bit of difference when deduplicating images.  I wouldn't be bitter if you removed this line, so long as you updated the schema as well.  But even if you don't mask this bit in the future, please wear a mask yourself, and save someone else from getting bit -- by the coronavirus!

**Comment by chushuai** [comment]
I don't understand why we need to use database to calculate Hamming distance，

I use facebook's open source faiss for fuzzy vector search，It can support billions of vector searches.@julescarbon

**Comment by infojunkie** [comment]
Thanks @julescarbon for the entertaining explanation. @chushuai we use the database to store the vectors, we don't have scalability problems (yet). I will let @DGaffney and @computermacgyver take over this issue.

**Comment by computermacgyver** [comment]
Closing this issue as we're now using PDQ. Phash support will be deprecated and removed.
Whether we use FAISS or Postgres, vectors have to be stored somewhere, and since we already use Postgres it made sense to store the vectors there. Now Postgres supports bit arrays, which is what we use for PDQ and what I would have used for phash to avoid that mysterious hack if it had been available. Thanks all.
